baseurl = "https://amirrezaghaderi.com/"
languageCode = "en-US"
title = "Amirreza Ghaderi"
Paginate = 30
disqusShortname = "amirrezablog"

pygmentsUseClasses = true
pygmentsCodeFences = true

[indexes]
tag = "topic"